- type: entity
  id: MiniGyroscopeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: mini gyroscope machine board
  components:
  - type: MachineBoard
    prototype: MiniGyroscope
    stackRequirements:
      Manipulator: 1
      Capacitor: 1
      Glass: 2

- type: entity
  id: JanitorialTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: janitorial techfab machine board
  description: A machine printed circuit board for a janitorial techfab.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: JanitorialTechFab
      stackRequirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker
