# For the veteran head of security cosmetics
- type: loadoutEffectGroup
  id: VeteranHOS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 180000 #50 hrs

- type: loadout
  id: HeadofSecurityVeteranHeadset
  equipment:
    ears: ClothingHeadsetHOSveteran
  effects:
  - !type:GroupLoadoutEffect
    proto: VeteranHOS
