- type: startingGear
  id: MobCargorillaGear
  equipment:
    ears: ClothingHeadsetCargo
    id: CargorillaIDCard

- type: startingGear
  id: GoblinRobeOSP
  equipment:
    outerClothing: ClothingOuterCoatRobesGoblin
    belt: ClothingBeltUtility
