# TODO: Add descriptions (many)
# TODO BODY: Part damage
- type: entity
  id: BasePart
  parent: BaseItem
  name: "body part"
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological
  - type: BodyPart
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
      - Trash

- type: entity
  id: BaseTorso
  name: "torso"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Torso
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 11
    staminaCost: 12

- type: entity
  id: BaseHead
  name: "head"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Head
    vital: true
  - type: Input
    context: "ghost"
  - type: Tag
    tags:
      - Head
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 5
    staminaCost: 5

- type: entity
  id: BaseLeftArm
  name: "left arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Left
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 7
    staminaCost: 7

- type: entity
  id: BaseRightArm
  name: "right arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Right
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 7
    staminaCost: 7

- type: entity
  id: BaseLeftHand
  name: "left hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Left
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 3

- type: entity
  id: BaseRightHand
  name: "right hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Right
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 3

- type: entity
  id: BaseLeftLeg
  name: "left leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Left
  - type: MovementBodyPart
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 8
    staminaCost: 9

- type: entity
  id: BaseRightLeg
  name: "right leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Right
  - type: MovementBodyPart
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 8
    staminaCost: 9

- type: entity
  id: BaseLeftFoot
  name: "left foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Left
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 4

- type: entity
  id: BaseRightFoot
  name: "right foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Right
  - type: DamageOtherOnHit # imp
    damage:
      types:
        Blunt: 4
