- type: entity
  id: MailTeleporterMachineCircuitboard
  parent: [ BaseComputerCircuitboard, BaseCargoContraband ]
  name: mail teleporter machine board
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: MailTeleporter
